GET http://localhost:3000

GET http://localhost:3000/users

POST http://localhost:3000/auth/create-account?email=hoon%40email.com&password=password&username=hoon

POST http://localhost:3000/auth/login?email=test%40email.com&password=password

